//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 11:04:33 AM CET 
//


package pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for keyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="keyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="field" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valuetype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fieldtype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mandatoryForPreservation" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="preservationPurpose" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "keyType")
public class KeyType {

    @XmlAttribute(required = true)
    protected String field;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String valuetype;
    @XmlAttribute(required = true)
    protected String fieldtype;
    @XmlAttribute(required = true)
    protected boolean mandatoryForPreservation;
    @XmlAttribute(required = true)
    protected boolean preservationPurpose;

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the valuetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuetype() {
        return valuetype;
    }

    /**
     * Sets the value of the valuetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuetype(String value) {
        this.valuetype = value;
    }

    /**
     * Gets the value of the fieldtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldtype() {
        return fieldtype;
    }

    /**
     * Sets the value of the fieldtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldtype(String value) {
        this.fieldtype = value;
    }

    /**
     * Gets the value of the mandatoryForPreservation property.
     * 
     */
    public boolean isMandatoryForPreservation() {
        return mandatoryForPreservation;
    }

    /**
     * Sets the value of the mandatoryForPreservation property.
     * 
     */
    public void setMandatoryForPreservation(boolean value) {
        this.mandatoryForPreservation = value;
    }

    /**
     * Gets the value of the preservationPurpose property.
     * 
     */
    public boolean isPreservationPurpose() {
        return preservationPurpose;
    }

    /**
     * Sets the value of the preservationPurpose property.
     * 
     */
    public void setPreservationPurpose(boolean value) {
        this.preservationPurpose = value;
    }

}
