//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 11:04:33 AM CET 
//


package pojo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaxPDVSize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="MaxPDVDocs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="ClassiDocumentali">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ClasseDocumentale" type="{}DocumentType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxPDVSize",
    "maxPDVDocs",
    "classiDocumentali"
})
@XmlRootElement(name = "PreservationConfiguration")
public class PreservationConfiguration {

    @XmlElement(name = "MaxPDVSize", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxPDVSize;
    @XmlElement(name = "MaxPDVDocs", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxPDVDocs;
    @XmlElement(name = "ClassiDocumentali", required = true)
    protected PreservationConfiguration.ClassiDocumentali classiDocumentali;

    /**
     * Gets the value of the maxPDVSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPDVSize() {
        return maxPDVSize;
    }

    /**
     * Sets the value of the maxPDVSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPDVSize(BigInteger value) {
        this.maxPDVSize = value;
    }

    /**
     * Gets the value of the maxPDVDocs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPDVDocs() {
        return maxPDVDocs;
    }

    /**
     * Sets the value of the maxPDVDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPDVDocs(BigInteger value) {
        this.maxPDVDocs = value;
    }

    /**
     * Gets the value of the classiDocumentali property.
     * 
     * @return
     *     possible object is
     *     {@link PreservationConfiguration.ClassiDocumentali }
     *     
     */
    public PreservationConfiguration.ClassiDocumentali getClassiDocumentali() {
        return classiDocumentali;
    }

    /**
     * Sets the value of the classiDocumentali property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreservationConfiguration.ClassiDocumentali }
     *     
     */
    public void setClassiDocumentali(PreservationConfiguration.ClassiDocumentali value) {
        this.classiDocumentali = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ClasseDocumentale" type="{}DocumentType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classeDocumentale"
    })
    public static class ClassiDocumentali {

        @XmlElement(name = "ClasseDocumentale", required = true)
        protected DocumentType classeDocumentale;

        /**
         * Gets the value of the classeDocumentale property.
         * 
         * @return
         *     possible object is
         *     {@link DocumentType }
         *     
         */
        public DocumentType getClasseDocumentale() {
            return classeDocumentale;
        }

        /**
         * Sets the value of the classeDocumentale property.
         * 
         * @param value
         *     allowed object is
         *     {@link DocumentType }
         *     
         */
        public void setClasseDocumentale(DocumentType value) {
            this.classeDocumentale = value;
        }

    }

}
